In [1]:
import numpy as np
import pandas as pd

## 1. Data Preparation

In [2]:
# Load Data
df_all = pd.read_csv('state_CA-IL.csv')
df_all_backup = df_all.copy()

G:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44,46) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
pd.options.display.max_columns = None
df_all.head()

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,derived_race,derived_sex,action_taken,purchaser_type,preapproval,loan_type,loan_purpose,lien_status,reverse_mortgage,open-end_line_of_credit,business_or_commercial_purpose,loan_amount,loan_to_value_ratio,interest_rate,rate_spread,hoepa_status,total_loan_costs,total_points_and_fees,origination_charges,discount_points,lender_credits,loan_term,prepayment_penalty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,property_value,construction_method,occupancy_type,manufactured_home_secured_property_type,manufactured_home_land_property_interest,total_units,multifamily_affordable_units,income,debt_to_income_ratio,applicant_credit_score_type,co-applicant_credit_score_type,applicant_ethnicity-1,applicant_ethnicity-2,applicant_ethnicity-3,applicant_ethnicity-4,applicant_ethnicity-5,co-applicant_ethnicity-1,co-applicant_ethnicity-2,co-applicant_ethnicity-3,co-applicant_ethnicity-4,co-applicant_ethnicity-5,applicant_ethnicity_observed,co-applicant_ethnicity_observed,applicant_race-1,applicant_race-2,applicant_race-3,applicant_race-4,applicant_race-5,co-applicant_race-1,co-applicant_race-2,co-applicant_race-3,co-applicant_race-4,co-applicant_race-5,applicant_race_observed,co-applicant_race_observed,applicant_sex,co-applicant_sex,applicant_sex_observed,co-applicant_sex_observed,applicant_age,co-applicant_age,applicant_age_above_62,co-applicant_age_above_62,submission_of_application,initially_payable_to_institution,aus-1,aus-2,aus-3,aus-4,aus-5,denial_reason-1,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2020,MV4O55SH8HO6KQSGW013,16984,IL,17043.0,1.704384e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,3,0,2,1,31,2,2,1,2,55000.0,85,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,300,36,1,2,1,2,2,245000,1,1,3,5,1,NaN,49.0,50%-60%,1,9,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2,2,6.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,2,2,3,3,2,2,55-64,25-34,Yes,No,1,1,6,NaN,NaN,NaN,NaN,1,2.0,NaN,NaN,6129,22.66,84800,113,2191,2066,36
1,2020,MV4O55SH8HO6KQSGW013,28100,IL,17091.0,1.709101e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Female,1,0,2,1,31,1,2,2,2,25000.0,23.478,4.19,1.78,2,0,NaN,0,NaN,NaN,240,NaN,NaN,2,2,2,2,115000,1,1,3,5,1,NaN,15.0,39,1,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,2,5,2,4,65-74,9999,Yes,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,1812,59.16,76500,50,340,498,48
2,2020,MV4O55SH8HO6KQSGW013,16984,IL,17043.0,1.704384e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,1,2,2,1,2,115000.0,85,4,1.12,2,NaN,NaN,NaN,NaN,NaN,300,36,1,2,1,2,2,735000,1,1,3,5,1,NaN,111.0,50%-60%,1,10,3.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,6.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,3,5,2,4,25-34,9999,No,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4668,43.12,84800,169,1159,1524,33
3,2020,MV4O55SH8HO6KQSGW013,16984,IL,17031.0,1.703181e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,White,Male,1,0,2,1,2,2,2,1,2,115000.0,84.876,3,0.13,2,NaN,NaN,NaN,NaN,NaN,300,36,1,2,1,2,2,385000,1,1,3,5,1,NaN,250.0,20%-<30%,1,10,2.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,2,4,5.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2,4,1,5,2,4,35-44,9999,No,NaN,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,5137,17.73,84800,105,1575,1800,58
4,2020,MV4O55SH8HO6KQSGW013,16984,IL,17031.0,1.703181e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,Race Not Available,Sex Not Available,1,0,2,1,31,1,2,1,2,215000.0,85,3,0.1,2,NaN,NaN,NaN,NaN,NaN,300,36,1,2,1,2,2,255000,1,1,3,5,1,NaN,143.0,20%-<30%,1,9,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2,2,6.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,2,2,3,3,2,2,35-44,45-54,No,No,1,1,6,NaN,NaN,NaN,NaN,10,NaN,NaN,NaN,4205,9.27,84800,235,1206,1335,76

In [4]:
# Add apporved_status from action_taken
approve_actions = [1,2,5,6,8]
reject_actions = [3,7]
df_all['approve_status'] = np.where(df_all['action_taken'].isin(approve_actions), 1, 0)
df_all['approve_status'] = np.where(df_all['action_taken']==4, np.nan, df_all['approve_status'])

In [5]:
## Get datasets by aproved/reject

# Dataset without withdrawn applications
cond_appr_rej = df_all['approve_status'].isin([1,0])
df_all_appr_rej = df_all.loc[cond_appr_rej]


# # Dataset with only approved loans
# cond_appr = df_all['approve_status'] == 1
# df_all_appr = df_all.loc[cond_appr]

# # Dataset with only rejected loans
# cond_rej = df_all['approve_status'] == 0
# df_all_rej = df_all.loc[cond_rej]

## Get datasets by States
cond_ca = df_all['state_code'] == 'CA'
cond_il = df_all['state_code'] == 'IL'

# Appr/rej in in IL
df_il_appr_rej = df_all_appr_rej[cond_il]

# # Approved data in CA
# df_ca_appr = df_all_appr.loc[cond_ca]

# # Approved data in IL
# df_il_appr = df_all_appr.loc[cond_il]

<ipython-input-5-7afd4e867a4c>:21: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_il_appr_rej = df_all_appr_rej[cond_il]

In [6]:
# Save dataset
# df_all_appr_rej.to_csv('df_all_appr_rej.csv')
# df_all_appr.to_csv('df_all_appr.csv')
# df_all_rej.to_csv('df_all_rej.csv')
df_il_appr_rej.to_csv('df_il_appr_rej.csv')
# df_ca_appr.to_csv('df_ca_appr.csv')
# df_il_appr.to_csv('df_il_appr.csv')